USE nclouds;
CREATE TABLE IF NOT EXISTS docker (ID INT NOT NULL AUTO_INCREMENT, name VARCHAR(50), email VARCHAR(50), password VARCHAR(30), PRIMARY KEY (ID));
GRANT ALL PRIVILEGES ON *.* TO 'nclouds_user'@'localhost';
FLUSH PRIVILEGES;
